name = "bijukaru-sync-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "BIJUKARU_SYNC"
class_name = "BijukaruSyncDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["BijukaruSyncDO"]
